variables:
  SampleName: DirectStorageSample
  CMakeConfig: -G "Visual Studio 16 2019" -A x64
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - deploy

build_dx12:
  tags:
  - windows
  - amd64
  stage: build
  artifacts:
    paths:
    - bin/
  script:
  - 'cmake -S . -B build/DX12 -DGFX_API=DX12 %CMakeConfig%'
  - 'cmake --build build/DX12 --config Release'

package_sample:
  tags:
  - windows
  - amd64
  stage: deploy
  dependencies:
    - build_dx12
  script:
  - echo cd .\bin\ > %SampleName%_DX12.bat
  - echo start %SampleName%_DX12.exe >> %SampleName%_DX12.bat
  artifacts:
      name: "$SampleName-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
      paths:
      - "bin/"
      - "license.txt"
      - "media/cauldron-media/"
      - "$SampleName_DX12.bat"
      - "readme.md"
